### ISSUE TITLE
Setup `dev` env

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#102]
1. Get AWS creds from Michael and setup all the services and frontends. 
2. Create bug tickets when you find something wrong in a service or frontend and let Michael know so we can get them fixed.

**Comment by cwshkut** [comment]
How should we do that? I guess here are the rules:
- all services should be run in separate EC2 instances
- all services should be attached to a single VPC
- frontend apps should be deployed as [Cloudfront distribution + S3 bucket] per each

**Comment by cwshkut** [comment]
Todo:
https://github.com/etenlab/docs/issues/105
