### ISSUE TITLE
Reset `dev` database

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#115]
- [x] clear the data and schema from the `eil_db_1` database
- [ ] drop the `eil_db_1_cp` database
- [x] restart the `database-api` and ensure it runs without error to setup the new schema
- [x] figure out how to test something to ensure the database is still working. 
- [x] create bug tickets for code owners if anything comes up

**Comment by cwshkut** [comment]
Dropping schemas and recreating `public`
```
DROP SCHEMA ADMIN CASCADE;
DROP SCHEMA public CASCADE;

CREATE SCHEMA public AUTHORIZATION postgres;
```

**Comment by cwshkut** [comment]
> figure out how to test something to ensure the database is still working.

The easiest way is to use [Showcase App](https://showcase.dev.lab.eten.bible) to ensure everything is set up well.

If we need some kind of smoke testing in runtime, we may implement that in `database-api` in some rest endpoint
