### ISSUE TITLE
Apply Bootstrap Graphic Design to Diegesis

### ISSUE THREAD

**Issue by mvahowe** [etenlab/docs#144]
repo: `ui-kit`
designs: [here](https://xd.adobe.com/view/bec91e7d-23c8-43ef-80d8-6d804367bea5-eb9a/?hints=off)
framework: `mui`

tasks:
- work in `ui-kit` and build out the designs linked above by building decoupled components.
- all components should be shown in storybook, including the final app.

**Comment by michaelmarshall** [comment]
I chatted with Mark. I don't want to edit his original post so here is the update. We will use MUI and the `ui-kit` repo and build out all the components necessary for the app design linked above. Be sure to click on everything to see all that the app will do.
