### ISSUE TITLE
Bug: Discrepancies in Data 

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#146]
repo: `oldb-app` and `oldb-api`

data source: https://airtable.com/shrPhY1QdKAo2vpIn/tblP4S88QrRjMrX3t
our app: https://oldb.dev.lab.eten.bible/sli/data/glottolog-language

Tasks: Determine why there are difference between the datasets and fix them.

The API should pull the data for each request so that the user can refresh and get the latest data.

**Comment by ForeverYoung1208** [comment]
There were several problems which lead to the data difference, all related to pagination params.
They are solved, but due to strange behaviour of airtable.js  with  paremeter 'offset', was used workaround with loading all the data from Airtable without pagination.
