### ISSUE TITLE
Refactor GitHub workflows

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#171]
Current workflows are printing secrets to the console. Refactor the workflow to not use insecure libs/practices. Prefer to use supported libs by known orgs.

**Comment by lucky-gru** [comment]
1. Well known actions

- **actions/checkout@v1**
   Well Known Action earned 3.8k stars.

- **actions/setup-node@v3**
   Well known action earned 2.8k stars.

- **aws-actions/configure-aws-credentials@v1**
   Well known action earned 1.7k stars.

- **docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9**
   Well known action earned 654 stars.

- **docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38**
   Well known action earned 573 stars.

- **docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc**
   Well known action earned 3.2k stars.

- **aws-actions/amazon-ecs-deploy-task-definition@v1**
   Well known action earned 498 stars.

2. Supported by individual contributors

- **dkershner6/aws-ssm-getparameters-action@v1**
   https://github.com/dkershner6/aws-ssm-getparameters-action
   earned 12 stars.
   reviewed, and no security issues, used standard modules.

- **xom9ikk/dotenv@v2**
   https://github.com/xom9ikk/dotenv
   earned 33 stars.
   reviewed, and no problem.

- **TimekillerTK/s3-sync-action@master**
   https://github.com/TimekillerTK/s3-sync-action
   earned 12 stars.
   reviewed, and no security issues, used standard modules.
