### ISSUE TITLE
Setup prod env

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#173]
Our prod env needs are currently small. We only have a couple apps to deploy. We don't need to deploy all the APIs and frontends.

Prod:
`oldb-app` repo and `oldb-api` repo use the `openlanguages.io` domain. They don't need any other APIs.
`crowd.Bible` repo uses the `crowd.bible` domain. It only needs the `cpg-server` API.
`cpg-server` uses the `api.crowd.bible` domain.

**Comment by michaelmarshall** [comment]
so we only need the following repos deploying:
oldb-app
oldb-api
crowd.Bible
cpg-server

**Comment by dinterr** [comment]
Considering all the dependencies we will need to deploy:

-  Database API: https://github.com/etenlab/database-api         => `db-api.crowd.bible`
-  OLDB API: https://github.com/etenlab/oldb-api                       =>  `api.openlanguages.io`
-  OLDB App: https://github.com/etenlab/oldb-app                     =>  `openlanguages.io`
-  CPG Server: https://github.com/etenlab/cpg-server                =>  `api.crowd.bible`
-  Crowd.Bible App: https://github.com/etenlab/crowd.Bible      =>  `crowd.bible`
-   Keycloak service                                                                         => `kc.crowd.bible`

Please also check the domain names.

**Comment by dinterr** [comment]
For the KeyCloak service, it has some comments asking to create a database manually: https://github.com/etenlab/infra/blob/main/config/dev.yaml#L280

Is it already done for prod environment?

**Comment by dinterr** [comment]
@michaelmarshall 
The production environment is set up:
 - https://db-api.crowd.bible/
 - https://api.crowd.bible/
 - https://keycloak.crowd.bible
 - https://openlanguages.io/
 - https://crowd.bible/home

Can you please let me know whether it works as you expect?

**Comment by dinterr** [comment]
There are some manual steps for setting up Keycloak database and adding secrets into the Secrets Manager for database connection. Unfortunately, it's not possible to run scripts in RDS to setup database. But this process can be automated with CloudFormatioin custom resources: https://aws.amazon.com/blogs/infrastructure-and-automation/use-aws-cdk-to-initialize-amazon-rds-instances/
Please let me know if this is something you want to implement?

**Comment by dinterr** [comment]
Regarding CI/CD pipelines for frontend apps. I can see that they are reading secrets from AWS SSM in the dev account. These secrets were created manually. Would you like me to set up the same files in the prod account?

**Comment by dinterr** [comment]
@michaelmarshall 
Two SSM secrets are added into prod account: `/prod/deploy/crowdbible/env` and `/prod/deploy/oldb-app/env`.
