### ISSUE TITLE
Bug in prod: oldb app not fetching data

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#190]
bug reproduction: view [this](https://openlanguages.io/sli/data/glottolog-language) page.

The data should be loaded like in the dev site [here](https://oldb.dev.lab.eten.bible/sli/data/glottolog-language)

**Comment by michaelmarshall** [comment]
both environments will use the same api secret for the air table data

**Comment by dinterr** [comment]
@michaelmarshall I updated the credentials and it is working now. Can you please check?

**Comment by michaelmarshall** [comment]
yup, thanks Roks!
