### ISSUE TITLE
Cleanup AWS dev env

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#202]
The dev env can now be made to be like the prod env. We'll lose all the old APIs. We'll use this as a good time to adjust some dns to have better named dev sites for crowd.Bible and openlanguages.io

1. Delete all the stacks in the dev env. 
2. Create a dev.crowd.bible zone in dev and point the prod zone nameservers to use the dev zone for `dev.crowd.bible`
3. Do the same ^^ for `dev.openlanguages.io` (which is the oldb app/api, fyi)
4. Rebuild the dev env with the same stuff as the prod env but pointing the apps/api to their dev equivalents.

**Comment by dinterr** [comment]
HI @michaelmarshall 
It is done. Please check the following URLs:
https://dev.openlanguages.io/
https://dev.crowd.bible/
https://api.dev.openlanguages.io/
https://api.dev.crowd.bible/
https://keycloak.dev.crowd.bible/
