### ISSUE TITLE
Basic Authentication Tests

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#241]
We need to start writing jest tests in crowd.Bible. let's start with verifying basic authentication. Aslam is the developer that has integrated the SSO service. Work with him on any issues with setting up the crowd.Bible repo and dev.crowd.Bible website for automated testing.

First basic tests just need to test the happy path. We don't want to create a lot of tests right now. We just need to focus on proving the user can perform basic tasks.

1. Ensure crowd.Bible is setup for jest tests.
2. User can register. After registration, user is automatically logged in.
3. User can login.
4. User can logout.
5. User can login after a logout.

**Comment by iPiyushPatel** [comment]
Sure @michaelmarshall thanks,

**Comment by iPiyushPatel** [comment]
Hello @michaelmarshall @aslambabu 
I've setup the local environments for Crowd.Bible and UI/Graphql is working on below URLs locally :

http://localhost:8201/graphql
http://localhost:8100/home

Can you please point to related UI and API's - Mutation/Queries and Flow if possible for the Auth tests so I can get started here ?

![image](https://github.com/etenlab/docs/assets/5212585/14cf31e0-83db-4402-96fe-a3666c5e1624)

![image](https://github.com/etenlab/docs/assets/5212585/642e2adb-00f6-42f1-acec-5df952b5209c)

Do let me know if I'm missing anything here.

Thanks,
