### ISSUE TITLE
Files API

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#46]
We need an API to upload files to a public S3 bucket.
1. Study the AWS recommended way to securely upload files to a bucket via a secure URL.
2. Create the DB schema and GraphQL API to upload and track files.
3. Use a personal AWS account to start developing, I will get you an IAM user in our `dev` account eventually. There shouldn't be any charges for doing light development. If there are, just expense them to Michael.
4. Implement a file upload widget in the showcase app.

**Comment by lucky-gru** [comment]
Will work on it. thanks Michael
