### ISSUE TITLE
Developer Experience and Onboarding Updates

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#59]
We need to ensure a new developer with nothing installed can easily setup our environment and get to work on any given repo.

Tasks:
1. Delete all your repos, env vars, and docker images/containers for any project we have.
2. in the repo `dev-env` run the `local` folder's `docker compose up` and ensure it successfully creates all micro-services and apps locally.
3. Update documentation to include any env vars or setup necessary. Get with the devs in each repo for knowledge transfers as needed.

**Comment by cwshkut** [comment]
https://github.com/etenlab/dev-env/pull/1
I think this PR might help other guys to set up faster :)

In general, docker-compose works fine.
The only thing not completely clear to me is why we explicitly set IP addresses for services. In docker-compose, everything works out-of-the-box

**Comment by cwshkut** [comment]
> database-api_1       | [Nest] 31  - 12/12/2022, 6:58:20 PM     LOG [RouterExplorer] Mapped {/ProgressBibleLanguageDetails, GET} route +1ms
database-api_1       | Creating database schema
database-api_1       | loading SQL: ./src/core/sql/schema/v1.schema.sql
database-api_1       | 
database-api_1       | /usr/src/etenlab/database-api/node_modules/pg-protocol/src/parser.ts:369
database-api_1       |       name === 'notice' ? new NoticeMessage(length, messageValue) : new DatabaseError(messageValue, length, name)
database-api_1       |                                                                     ^
database-api_1       | error: syntax error at or near "("
database-api_1       |     at Parser.parseErrorMessage (/usr/src/etenlab/database-api/node_modules/pg-protocol/src/parser.ts:369:69)
database-api_1       |     at Parser.handlePacket (/usr/src/etenlab/database-api/node_modules/pg-protocol/src/parser.ts:188:21)
database-api_1       |     at Parser.parse (/usr/src/etenlab/database-api/node_modules/pg-protocol/src/parser.ts:103:30)
database-api_1       |     at Socket.<anonymous> (/usr/src/etenlab/database-api/node_modules/pg-protocol/src/index.ts:7:48)
database-api_1       |     at Socket.emit (node:events:513:28)
database-api_1       |     at addChunk (node:internal/streams/readable:315:12)
database-api_1       |     at readableAddChunk (node:internal/streams/readable:289:9)
database-api_1       |     at Socket.Readable.push (node:internal/streams/readable:228:10)
database-api_1       |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

When I execute `/src/core/sql/schema/v1.schema.sql` directly on the server, the query goes without errors. Chances are the problem has been fixed but not delivered to Dockerhub. 
Will try running that outside the container

**Comment by cwshkut** [comment]
The docker image of `database_api` is outdated. When running the most recent version of the service directly, it successfully executes the migration. After that, the container starts without errors.

**Comment by cwshkut** [comment]
Another point:
https://github.com/etenlab/database-api

Command `npm ci` fails due to conflicting dependencies' versions. Since `npm ci` is a convenient, fast and predictable way to install dependencies, it can also be considered as an issue with _development experience_

**Comment by michaelmarshall** [comment]
The github workflow updates the docker image, so I'm wondering if that has silently failed sometimes. 
If `npm ci` fails for version conflicts, do we just need to have a dev update versions?

**Comment by cwshkut** [comment]
Yes, we need to resolve the conflicts by picking the right version for each conflicting package. If it is possible

**Comment by michaelmarshall** [comment]
ya i'm worried that some won't be possible. Could you please make a ticket for this in the `approved` column with the appropriate screen shots and user experience?

**Comment by cwshkut** [comment]
IDK why I got the issue back in the day, but currently it is not reproducible. `npm ci` goes well. I think it's not relevant anymore

**Comment by cwshkut** [comment]
By this moment docker-compose-default successfully starts all the services. I think this task can be closed
