### ISSUE TITLE
data-table HOC

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#63]
This job is to create the first draft of a data-table HOC (higher order component). This will be a react component that might eventually take other components as parameters, but for the first draft will only take table meta data and/or graphql queries.

Tasks:
1. Setup a database and pgAdmin via `docker compose` in the `dev-env` repo.
2. Setup the `showcase` app on localhost.
3. Load data into your database. Aslam has recently worked on some automating in the `data-load-api` repo so ask him for any updates, otherwise use the `scripts` and `datasets` repo for the files to run.
4. Observe the current `Dataset.tsx` [file](https://github.com/etenlab/showcase/blob/main/src/components/Dataset.tsx) in the `showcase` repo.
5. In the `eil-data-table` repo, create a `data-table` component and publish it to npm. Give Michael your npm username/email to get access to the org on npm.
6. Refactor showcase to use the new component from npm.

You'll need to study how we get data via graphql and ensure the data table is parameterized for those queries. You are creating a generic data table view that will use our graphql frontend types/url to learn about the columns and rows. In the future we will want the table rows to be clickable and accordion-open into a detail view between the rows. We don't have wireframes for this yet so you'll need to use the current app as a reference. 

For the table component you are free to consider different table libraries. We need a fully featured table view. material table and AG Grid are powerful. Remember, in the future we'll add lots of stuff to this component.

**Comment by michaelmarshall** [comment]
This job is to create the first draft of a data-table HOC (higher order component). This will be a react component that might eventually take other components as parameters, but for the first draft will only take table meta data and/or graphql queries.

Tasks:
1. Setup a database and pgAdmin via `docker compose` in the `dev-env` repo.
2. Setup the `showcase` app on localhost.
3. Load data into your database. Aslam has recently worked on some scripts so ask him for any updates, otherwise use the `scripts` and `datasets` repo for the files to run.
4. Observe the current `Dataset.tsx` [file](https://github.com/etenlab/showcase/blob/main/src/components/Dataset.tsx) in the `showcase` repo.
5. In the `eil-data-table` repo, create a `data-table` component and publish it to npm. Give Michael your npm username/email to get access to the org on npm.
6. Refactor showcase to use the new component from npm.

You'll need to study how we get data via graphql and ensure the data table is parameterized for those queries. You are creating a generic data table view that will use our graphql frontend types/url to learn about the columns and rows. In the future we will want the table rows to be clickable and accordion-open into a detail view between the rows. We don't have wireframes for this yet so you'll need to use the current app as a reference. 

For the table component you are free to consider different table libraries. We need a fully featured table view. material table and AG Grid are powerful. Remember, in the future we'll add lots of stuff to this component.

**Comment by cwshkut** [comment]
The accordion feature has not been implemented, but the library supports row expanding.

Here is the PR: https://github.com/etenlab/showcase/pull/3
