### ISSUE TITLE
Load Strong's into database via Graph Schema

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#66]
We need to load scripture and the Strong's word list into the graph. Talk with Michael about this first.

___ is the main dev for this ticket, Jake has the proskomma/Diegesis experience needed for one of the steps. So we need to have a knowledge transfer.

Tasks:
1. View schema for Strong's data to be stored on original language (Hebrew/Greek) words. [link](https://miro.com/app/board/uXjVPTadGVs=/?share_link_id=453993093488)
2. Talk to Jake about using Proskomma data.
3. Load English scripture into graph including Strong's word references: [link](https://github.com/etenlab/datasets/blob/main/scripture/eng-t4t_usfm/02-GENeng-t4t.usfm) by using Proskomma/Diegesis to parse the `.usfm` document.
4. View Strong's data: [link](https://github.com/etenlab/usq/blob/main/scripts/data/strongs-hebrew-dictionary.ts) and load into graph. Ensure the scripture data and Strong's words are linked.

![Screen Shot 2022-12-12 at 4 19 51 PM](https://user-images.githubusercontent.com/1165460/207167521-b68e46c0-4d7f-4a99-bb42-d0f1d407c40c.png)

**Comment by cwshkut** [comment]
The task was done in the `data-load-api` repo.
What has been done within this task:
- building graph nodes/relations and saving them into DB with batches (`src/strongs/strongs.service.ts`).
- filling database with Strongs entries (`POST /strongs/create`)
- parsing USFM into tags (`src/scripture/usfmParser.ts`)
- building a graph from an input scripture file and saving it into DB. Root node: `book`, leaf nodes: `strong-entry`, `addition`
- resolving the graph from a given node id (`GET /graph/from-node/{id}`)

**Comment by cwshkut** [comment]
Here is a graph sample gotten with `GET /graph/from-node/{id}`. The input file for that graph is the first two chapters of [Genesis](https://raw.githubusercontent.com/etenlab/datasets/main/scripture/eng-t4t_usfm/02-GENeng-t4t.usfm) ([cut version](https://raw.githubusercontent.com/etenlab/data-load-api/main/src/scripture/example_c1-2.usfm))
[Sample.txt](https://github.com/etenlab/docs/files/10457994/response_1674133511475.txt)

**Comment by cwshkut** [comment]
Notes:
- Splitting a verse into sentences is implemented by using `.`, `?`, `!` as breakpoints. If a verse includes `(`, `"`, `'`, splitting into sentences is omitted and the whole verse is treated as a sentence.
- Only downstream graph resolving is implemented (traversing by outgoing relationships only)
