### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#68]
The docs repo, `docs`, has recently been updated by Vivek to use docusaraus. We need to now use this to document our standards, developer onboarding, etc. Take a look at the docs and delete anything that isn't needed and begin accumulating information for all the devs (and your experience) that we need to put in there.

**Comment by cwshkut** [comment]
The doc for onboarding is done. Further steps:
1. Fix `aggregation-api` service so it runs successfully within docker-compose
2. Adjust docker-compose
3. Adjust the docs (if needed).

**Comment by cwshkut** [comment]
1. Aggregation has been fixed (some services lacked some graphql directives)
2. docker-compose works well (https://github.com/etenlab/docs/issues/59)
3. The docs regarding the docker-compose are completed.

The only thing to do is to `mv docker-compose-default.yml docker-compose.yml`

**Comment by cwshkut** [comment]
> The only thing to do is to mv docker-compose-default.yml docker-compose.yml (which is not directly related to this task)

That has been done, so this task can be closed
