### ISSUE TITLE
Data Table HOC v2

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#73]
Update the `data-table` component to OPTIONALLY take a param to enable discussion on each row. Each row would then include a discussion icon and, when clicked, would open up a discussion box under the row. If a box under the row is too hard for now, then just do a discussion box somewhere else, like below the table, as a modal, or appearing from offscreen as an overlay/menu.

Hiroshi is our discussion developer so get with him for any usage questions/issues with his component.

**Comment by cwshkut** [comment]
Unfortunately, AG-Grid's `details` feature is available for the enterprise edition only. Without that, it is hard to implement row expanding. I have tried the `full-width row` feature, but that also comes with limitations. I think for MUI tables we will have the same issues.
So far putting discussions under the table seems to be the simplest way to go.

**Comment by cwshkut** [comment]
Managed to implement expanding rows myself

**Comment by cwshkut** [comment]
The component is done. Current implementation:
- optional row expanding on click
- optional left/right icon
- each field of the row can have different content when expanded
- Discussion-box is not in-built in the component. It must be provided as a prop:
```js
{
   // ... other props
   endIcon: ForumIcon,
   detailRenderer: (row: any) => (
      <Discussion
         rowId={row.id} // TODO: determine row keys somehow if row has no id
         ableName={tableName}
         userId={USER_ID_STUB} // TODO: configure auth
      />
),
```
