### ISSUE TITLE
Strong's Data UI + Components

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#74]
[wireframes](https://www.figma.com/file/md8nAIVfMUNxGhkofGhP6c/Wireframes?node-id=0%3A1&t=z6JvYVQGUvsgmUv4-1)

Discuss with Michael. This UI doesn't expose any mutations. We are only reading data out. Strong's data is just one type of meta-data/relationship-data we will have. Many more types of data will be coming.

Breakdown the UI into components and consider publishing important components to npm. Get with Michael to do that.

**Comment by michaelmarshall** [comment]
![Image](https://user-images.githubusercontent.com/1165460/213495610-ae060a9f-de5c-4628-bd5f-fac82b82dc80.png)

**Comment by cwshkut** [comment]
Implemented in `showcase`: src/components/StrongsWords.tsx
